In [90]:
import pandas as pd

In [91]:
df=pd.read_csv(r"D:\new\OneDrive\Desktop\BMW\25BTIT149_THARUN KR.csv")

In [92]:
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

In [93]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10782 entries, 0 to 10781
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         10782 non-null  str
 1   year          10782 non-null  int64
 2   price         10782 non-null  int64
 3   transmission  10782 non-null  str
 4   mileage       10782 non-null  int64
 5   fuelType      10782 non-null  str
 6   tax           10782 non-null  int64
 7   mpg           10782 non-null  float64
 8   engineSize    10782 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 986.9 KB

In [94]:
df.sample(15)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
623,3 Series,2017,14998,Manual,13309,Petrol,150,48.7,2.0
6273,7 Series,2019,48912,Semi-Auto,6516,Diesel,150,44.8,3.0
580,1 Series,2018,17498,Semi-Auto,17063,Petrol,145,36.7,2.0
8530,4 Series,2016,13795,Automatic,80950,Diesel,30,65.7,2.0
8055,2 Series,2015,11499,Manual,48937,Diesel,30,62.8,2.0
8899,1 Series,2016,11500,Manual,54156,Diesel,30,65.7,2.0
10059,X1,2017,19490,Automatic,27988,Diesel,145,57.6,2.0
9354,2 Series,2016,16359,Automatic,17748,Diesel,125,57.6,2.0
573,3 Series,2019,23498,Semi-Auto,7516,Diesel,145,54.3,2.0
8415,1 Series,2015,9799,Manual,49096,Diesel,20,68.9,2.0
3546,5 Series,2019,28000,Semi-Auto,3102,Petrol,145,50.4,2.0
4731,X3,2018,30980,Semi-Auto,4813,Diesel,145,54.3,2.0
10623,4 Series,2015,12800,Manual,56741,Diesel,30,62.8,2.0
5583,1 Series,2015,11295,Automatic,27054,Diesel,20,72.4,1.5
10374,1 Series,2016,10700,Manual,33489,Diesel,0,83.1,1.5

In [95]:
df['model'].value_counts()

model
 3 Series    2443
 1 Series    1969
 2 Series    1229
 5 Series    1056
 4 Series     995
 X1           804
 X3           551
 X5           468
 X2           288
 X4           179
 M4           125
 6 Series     108
 Z4           108
 7 Series     106
 X6           106
 X7            55
 i3            43
 8 Series      39
 M5            29
 M3            27
 M2            21
 i8            17
 M6             8
 Z3             7
X2              1
Name: count, dtype: int64

In [96]:
df2=df.loc[df['model'].str.contains('series', case=False)]

In [97]:
df2['model'].value_counts()

model
3 Series    2443
1 Series    1969
2 Series    1229
5 Series    1056
4 Series     995
6 Series     108
7 Series     106
8 Series      39
Name: count, dtype: int64

In [98]:
df2['model'] = df2['model'].str.replace(' Series', '', regex=False)

In [99]:
df2['model'].value_counts()

model
3    2443
1    1969
2    1229
5    1056
4     995
6     108
7     106
8      39
Name: count, dtype: int64