In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_excel('Online Retail.xlsx')

In [3]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [4]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [6]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

# Data Copy

In [7]:
df2 = df.copy()

In [8]:
df2 = df2.drop_duplicates()

In [9]:
df2['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [10]:
df2['TotalPrice'] = df2['Quantity'] * df2['UnitPrice']

In [11]:
df2['TotalPrice'].sum()

np.float64(9726006.954)

In [12]:
df2['CustomerID'].nunique()

4372

In [13]:
df2['Description'].nunique()

4223

In [14]:
df2.groupby("Country")["TotalPrice"].sum().sort_values(ascending=False)

Country
United Kingdom          8167128.184
Netherlands              284661.540
EIRE                     262993.380
Germany                  221509.470
France                   197317.110
Australia                137009.770
Switzerland               56363.050
Spain                     54756.030
Belgium                   40910.960
Sweden                    36585.410
Japan                     35340.620
Norway                    35163.460
Portugal                  29302.970
Finland                   22326.740
Channel Islands           20076.390
Denmark                   18768.140
Italy                     16890.510
Cyprus                    12858.760
Austria                   10154.320
Hong Kong                  9908.240
Singapore                  9120.390
Israel                     7901.970
Poland                     7213.140
Unspecified                4740.940
Greece                     4710.520
Iceland                    4310.000
Canada                     3666.380
Malta                      2505.470
United Arab Emirates       1902.280
USA                        1730.920
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1291.750
Brazil                     1143.600
RSA                        1002.310
Czech Republic              707.720
Bahrain                     548.400
Saudi Arabia                131.170
Name: TotalPrice, dtype: float64

In [15]:
df2['Date']=pd.to_datetime(df2['InvoiceDate'])
df2['year']=df2['Date'].dt.year
df2['month']=df2['Date'].dt.month
df2['day']=df2['Date'].dt.day
df2['dat_of_week']=df2['Date'].dt.day_of_week
df2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Date,year,month,day,dat_of_week
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12-01 08:26:00,2010,12,1,2
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-01 08:26:00,2010,12,1,2
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12-01 08:26:00,2010,12,1,2
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-01 08:26:00,2010,12,1,2
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-01 08:26:00,2010,12,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,2011-12-09 12:50:00,2011,12,9,4
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12-09 12:50:00,2011,12,9,4
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12-09 12:50:00,2011,12,9,4
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12-09 12:50:00,2011,12,9,4
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12-09 12:50:00,2011,12,9,4

In [16]:
for col in df2.select_dtypes(include="object").columns:
    df2[col] = df2[col].astype("string").str.lower()

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    536641 non-null  string
 1   StockCode    536641 non-null  string
 2   Description  535187 non-null  string
 3   Quantity     536641 non-null  int64
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      536641 non-null  string
 8   TotalPrice   536641 non-null  float64
 9   Date         536641 non-null  datetime64[ns]
 10  year         536641 non-null  int32
 11  month        536641 non-null  int32
 12  day          536641 non-null  int32
 13  dat_of_week  536641 non-null  int32
dtypes: datetime64[ns](2), float64(3), int32(4), int64(1), string(4)
memory usage: 53.2 MB

In [18]:
TotalQuantity = df2.groupby("CustomerID")["Quantity"].sum()

In [19]:
TotalSpent = df2.groupby("CustomerID")["TotalPrice"].sum()

In [20]:
NumberOfOrders = df2.groupby("CustomerID")["InvoiceNo"].nunique()

In [21]:
UniqueProducts = df2.groupby("CustomerID")["StockCode"].nunique()

In [22]:
AverageOrderValue = df2.groupby("CustomerID")["TotalPrice"].mean()

In [23]:
customer_df = pd.concat([
    TotalQuantity,
    TotalSpent,
    NumberOfOrders,
    AverageOrderValue,
    UniqueProducts
], axis=1)

In [24]:
customer_df.columns = ['TotalQuantity', 'TotalSpent', 'NumberOfOrders', 'AvgOrderValue', 'UniqueProducts']

In [25]:
customer_df

,TotalQuantity,TotalSpent,NumberOfOrders,AvgOrderValue,UniqueProducts
CustomerID,,,,,
12346.0,0,0.00,2,0.000000,1
12347.0,2458,4310.00,7,23.681319,103
12348.0,2341,1797.24,4,57.975484,22
12349.0,631,1757.55,1,24.076027,73
12350.0,197,334.40,1,19.670588,17
...,...,...,...,...,...
18280.0,45,180.60,1,18.060000,10
18281.0,54,80.82,1,11.545714,7
18282.0,98,176.60,3,13.584615,12
18283.0,1357,2045.53,16,2.837074,263
18287.0,1586,1837.28,3,26.246857,59

In [26]:
df2['Country'].value_counts()

Country
united kingdom          490300
germany                   9480
france                    8541
eire                      8184
spain                     2528
netherlands               2371
belgium                   2069
switzerland               1994
portugal                  1510
australia                 1258
norway                    1086
italy                      803
channel islands            757
finland                    695
cyprus                     611
sweden                     461
unspecified                442
austria                    401
denmark                    389
japan                      358
poland                     341
israel                     294
usa                        291
hong kong                  284
singapore                  229
iceland                    182
canada                     151
greece                     146
malta                      127
united arab emirates        68
european community          61
rsa                         58
lebanon                     45
lithuania                   35
brazil                      32
czech republic              30
bahrain                     19
saudi arabia                10
Name: count, dtype: Int64

In [27]:
snapshot_date = df2['Date'].max() + pd.Timedelta(days=1)
recency = df2.groupby('CustomerID')['Date'].max().apply(lambda x: (snapshot_date - x).days)
customer_df['Recency'] = recency

customer_df.describe()

,TotalQuantity,TotalSpent,NumberOfOrders,AvgOrderValue,UniqueProducts,Recency
count,4372.000000,4372.000000,4372.000000,4372.000000,4372.000000,4372.000000
mean,1119.133349,1893.531433,5.075480,28.868389,61.211116,92.047118
std,4672.995712,8218.696204,9.338754,127.324719,85.425119,100.765435
min,-303.000000,-4287.630000,1.000000,-4287.630000,1.000000,1.000000
25%,151.750000,291.795000,1.000000,11.066618,15.000000,17.000000
50%,364.000000,644.070000,3.000000,16.941019,35.000000,50.000000
75%,956.250000,1608.335000,5.000000,23.581429,77.000000,143.000000
max,196719.000000,279489.020000,248.000000,3861.000000,1794.000000,374.000000

In [28]:
threshold = customer_df['TotalSpent'].quantile(0.75)
customer_df['SpendClass'] = np.where(customer_df['TotalSpent'] >= threshold, 'High', 'Low')
customer_df['SpendClass'].value_counts()

SpendClass
Low     3279
High    1093
Name: count, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

features = ['TotalQuantity', 'NumberOfOrders', 'AvgOrderValue', 'UniqueProducts', 'Recency']
X = customer_df[features]
y = LabelEncoder().fit_transform(customer_df['SpendClass'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train.shape, X_test.shape

((3497, 5), (875, 5))

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,roc_auc_score

models = {
    'LogisticRegression': LogisticRegression(max_iter=1000, class_weight='balanced'),
    'DecisionTreeClassifier': DecisionTreeClassifier(max_depth=5, random_state=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    preds = model.predict(X_test_scaled)
    probs = model.predict_proba(X_test_scaled)[:, 1]

    print(classification_report(y_test, preds))
    auc = roc_auc_score(y_test, probs)
    print("ROC-AUC:", round(auc, 4))
    print()

    results[name] = {'model': model, 'preds': preds, 'probs': probs, 'auc': auc}

              precision    recall  f1-score   support

           0       0.78      0.89      0.83       219
           1       0.96      0.92      0.94       656

    accuracy                           0.91       875
   macro avg       0.87      0.90      0.89       875
weighted avg       0.92      0.91      0.91       875

ROC-AUC: 0.9769

              precision    recall  f1-score   support

           0       0.88      0.86      0.87       219
           1       0.95      0.96      0.96       656

    accuracy                           0.94       875
   macro avg       0.92      0.91      0.92       875
weighted avg       0.94      0.94      0.94       875

ROC-AUC: 0.9619